name: "Update data"

on: push

jobs:
  update-data:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update data.json
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: node update-data.js
