name: "Update data"

on: push

jobs:
  update-data:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update data.json
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
      - run: yarn
      - name: Run update script
      - run: node update-data.js
      - name: Commit new data file
      - run: git commit -m ":sparkles: Automatically update data.json"

