name: "Update data"

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update data.json
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run update script
        run: node update-data.js

      - name: Update script_ran_at file
        run: echo "$(date +%F)" > script_ran_at

      - name: Commit files
        run: |
          git config --local user.name "albingroen"
          git add .
          git commit -m "Automatically update data.json"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
